Javascript/javascript3/week2
islam-fawzy25/hyf-homework pull request #12
Opened 2021-03-16 19:44 UTC by islam-fawzy25

2021-03-21 07:40 UTC, Deepti-Dk requested changes
Very nicely done :-)
just some minor changes to be done.

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/promise-visual/main.js
> +    // moveElement functions inside promise.all and i did not call promise.all and
Promise.all has to be called inside a function(translateAllAtOnce) to be executed at a function call else its getting executed in sequence like normal code. 
Code is working fine with async-await and the solution could be made using async-await or Promise.all as per HW:-)

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/promise-visual/main.js
> +
Please remove blank lines

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/homework/main.js
> +
In the exercise its written 'When you have written the promise, use it with async/await'. I think you missed async/await part :-)

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/homework/main.js
> +  const delayPromis = new Promise((resolve) => {
typo in const name delayPromis

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/homework/main.js
> +  const movie = await getUrl.json()
minor thing but const name should be 'movies' instead of 'movie' :-)

2021-03-21 07:40 UTC, Deepti-Dk commented on javascript/javascript3/week2/homework/main.js
> +
blank lines, again :-)

2021-03-23 12:28 UTC, islam-fawzy25 commented on javascript/javascript3/week2/homework/main.js
> +
> In the exercise its written 'When you have written the promise, use it with async/await'. I think you missed async/await part :-)

Hi Deepti ;
thanks for your comments , but at this part i think they did not mention somthing about async /await i copied :
Promise that resolves after set time
Create a function that has one parameter: resolveAfter. Calling this function will return a promise that resolves after the resolveAfter seconds has passed.

Here is an example of how to use the promise

makeUpYourOwnFunctionName(8).then(() => {
  console.log("I am called asynchronously"); // logged out after 8 seconds
});

2021-03-23 18:35 UTC, islam-fawzy25 commented on javascript/javascript3/week2/homework/main.js
> +
> In the exercise its written 'When you have written the promise, use it with async/await'. I think you missed async/await part :-)

yes , you are right it was on last line so , i did not saw that . Thanks

2021-03-23 18:37 UTC, merged

2021-03-23 18:46 UTC, Deepti-Dk commented
No problem :-)

On Tue, 23 Mar 2021 at 19:35, islam-fawzy25 ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In javascript/javascript3/week2/homework/main.js
> <https://github.com/islam-fawzy25/hyf-homework/pull/12#discussion_r599835689>
> :
>
> > +
> +//Promise that resolves after set time
> +async function delay(resolveAfter) {
> +  const delayPromis = new Promise((resolve) => {
> +    setTimeout(() => {
> +      resolve()
> +    }, 1000 * resolveAfter);
> +  })
> +  return delayPromis
> +}
> +
> +delay(8).then(() => {
> +  console.log("I am called asynchronously after 8 seconds");
> +  // logged out after 8 seconds
> +});
> +
>
> In the exercise its written 'When you have written the promise, use it
> with async/await'. I think you missed async/await part :-)
>
> yes , you are right it was on last line so , i did not saw that . Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/islam-fawzy25/hyf-homework/pull/12#discussion_r599835689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6WMQONJQRNLDJL3UDOR33TFDNQFANCNFSM4ZJGTHVQ>
> .
>