Nodejs/week2
islam-fawzy25/hyf-homework pull request #24
Opened 2021-05-03 21:05 UTC by islam-fawzy25

2021-05-06 19:25 UTC, florinmaticu commented on nodejs/week2/homework/warmup/web.js
> +  const first = parseInt(req.query.first);
The code would not work correctly if the parameters are not numbers.
GET /numbers/add?first=abc&second=ggdsdfs

2021-05-06 19:30 UTC, florinmaticu requested changes

2021-05-06 19:30 UTC, florinmaticu commented on nodejs/week2/homework/warmup/web.js
> +    const first = parseInt(req.params.first);
The code would not work correctly if the parameters are not numbers.
`GET /numbers/multiply/abbv/ghhd`

2021-05-06 19:30 UTC, florinmaticu commented on nodejs/week2/homework/meal-sharing/src/backend/api/reviews-router.js
> +    throw error;
throwing an error here is not helpful because it would crash your server app if it's not caught.
you can return an error code like `500 Internal Server Error` instead

2021-05-06 19:33 UTC, florinmaticu commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +    throw error;
throwing an error here is not helpful because it would crash your server app if it's not caught.
you can return an error code like` 500 Internal Server Error `instead

2021-05-06 19:33 UTC, florinmaticu commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +    throw error;
throwing an error here is not helpful because it would crash your server app if it's not caught.
you can return an error code like` 500 Internal Server Error` instead

2021-05-06 19:41 UTC, florinmaticu commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +router.get("/:id", (request, response) => {
you have an array of json objects...and i think that you want to compare  the id of each json object with the one from the get request...      const selectedMeals = meals.filter(meal => meal.id === id);

2021-05-09 21:49 UTC, islam-fawzy25 commented
Thanks Alot Florin for your helpful comments I checked all points and it was really good practice

2021-05-09 21:59 UTC, merged