Javascript/javascript1/week2
islam-fawzy25/hyf-homework pull request #5
Opened 2021-01-31 09:18 UTC by islam-fawzy25

2021-01-31 13:48 UTC, florinmaticu requested changes

2021-01-31 13:48 UTC, florinmaticu commented on javascript/javascript1/week2/Event-application.js
> +var dd = String(today.getDate()).padStart(2, '0');
I am not sure this work since **dd** is a **string** and you try to add a string with a number.  I believe you need to add number + number.

2021-01-31 13:48 UTC, florinmaticu commented on javascript/javascript1/week2/StudentManager.js
> +  if( typeof (studentName) !== "string" ){
i belive you want something like this...Empty string `""`is still a valid string 
```suggestion
  if ( studentName !== "" ){
```

2021-01-31 13:48 UTC, florinmaticu commented on javascript/javascript1/week2/StudentManager.js
> +      return console.log('Stuednt '+studentName+' is already in the class')
I think you want to return a string and not the result of the console.log(...)
you could something like this  console.log(addStudentToClass(studentName))
```suggestion
      return 'Student'+studentName+' is already in the class'
```

2021-02-01 09:38 UTC, islam-fawzy25 commented on javascript/javascript1/week2/Event-application.js
> +var dd = String(today.getDate()).padStart(2, '0');
it is working  with string , when i console.log (dd) it giving me number of the day like today 01 " like i mention on top i found it on websit "
but my question now is :  function getEventWeekday(newDate){
   return weekdays [(dd+ newDate)%7] ; this function should start from today (dd) i tried today is Monday and in array also but its giving me 'Wednesday* if i console.log (getEventWeekday(1)

2021-02-01 09:49 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +  if( typeof (studentName) !== "string" ){
ok Thanks 
done

2021-02-01 10:00 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +      return console.log('Stuednt '+studentName+' is already in the class')
i tried to do that but it dose not working , it did not implement the statement  when i re add the same name it giving me : 
 console.log('Student '+studentName +' is added to the class') it is the last else in function .

2021-02-01 10:10 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +  if( typeof (studentName) !== "string" ){
but after i did that changes if i add number it says ok and added it like student

2021-02-02 19:34 UTC, florinmaticu commented on javascript/javascript1/week2/Event-application.js
> +var dd = String(today.getDate()).padStart(2, '0');
Okay

2021-02-02 19:39 UTC, florinmaticu commented on javascript/javascript1/week2/StudentManager.js
> +      return console.log('Stuednt '+studentName+' is already in the class')
const response = 'Student'+studentName+' is already in the class';
return response,;

2021-02-03 10:57 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +      return console.log('Stuednt '+studentName+' is already in the class')
![Screenshot (3)](https://user-images.githubusercontent.com/75618135/106737122-9892c000-6616-11eb-9f8d-97c99b16e8b0.png)
![Screenshot (4)](https://user-images.githubusercontent.com/75618135/106737215-b3fdcb00-6616-11eb-9b2d-6c92da8eaed2.png)

Thank for helping , but i still don´t understand what do you mean at :you could do something like this console.log(addStudentToClass(studentName))

you mean like i did here or the same order inside if  statement 
Thanks in Advance

2021-02-03 11:06 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +  if( typeof (studentName) !== "string" ){
![Screenshot (5)](https://user-images.githubusercontent.com/75618135/106738167-e5c36180-6617-11eb-9c11-92db368b81aa.png)
![Screenshot (6)](https://user-images.githubusercontent.com/75618135/106738172-e6f48e80-6617-11eb-8ad2-a03f46fe4c67.png)
it is working fine with ( typeof (studentName) != "string"|| studentName ==' ') and i add or studentName ==' ' so it is avoid empty space

2021-02-03 11:15 UTC, islam-fawzy25 commented on javascript/javascript1/week2/Event-application.js
> +var dd = String(today.getDate()).padStart(2, '0');
![Screenshot (7)](https://user-images.githubusercontent.com/75618135/106739456-75b5db00-6619-11eb-8160-a7e4f12d47ed.png)
![Screenshot (8)](https://user-images.githubusercontent.com/75618135/106739458-76e70800-6619-11eb-8e51-42f820d72961.png)

2021-02-03 11:19 UTC, islam-fawzy25 commented on javascript/javascript1/week2/StudentManager.js
> +      return console.log('Stuednt '+studentName+' is already in the class')
so i think now  can i merge PR ?

2021-02-04 09:29 UTC, merged