Javascript/javascript1/week3
islam-fawzy25/hyf-homework pull request #6
Opened 2021-02-02 20:00 UTC by islam-fawzy25

2021-02-05 18:29 UTC, aina21 requested changes
Nice job :+1:

2021-02-05 19:29 UTC, islam-fawzy25 commented on javascript/javascript1/week3/homework.js
> +    let travel = new Array();
i did like i found at somewhere " let travel = new Array();
     travel = travelHistory.split('.'); "
but its good short cut 
thanks

2021-02-05 19:39 UTC, islam-fawzy25 commented on javascript/javascript1/week3/homework.js
> +     travelTime= travel[0]+ ' hours '+ minutesCalculation +' minutes'
sorry i can not got it ,

2021-02-05 20:00 UTC, islam-fawzy25 commented on javascript/javascript1/week3/Step3.js
> +   if ( notes[i].id == id ){
you mean true as boolean or true as variable ?
i tried to do that as boolean and it give Error
![Screenshot (9)](https://user-images.githubusercontent.com/75618135/107082808-04cb1a80-67f5-11eb-99bf-de41b46040d9.png)

2021-02-05 20:22 UTC, islam-fawzy25 commented on javascript/javascript1/week3/homework.js
> +        names.splice(names.indexOf (nameToRemove),1)
i can not got it 
i removed for loop , so i did not remove the nameToRemove 
![Screenshot (10)](https://user-images.githubusercontent.com/75618135/107085097-401b1880-67f8-11eb-838c-2fbaa3c299b5.png)

2021-02-06 16:28 UTC, islam-fawzy25 commented on javascript/javascript1/week3/homework.js
> +        names.splice(names.indexOf (nameToRemove),1)
perfect , thank you

2021-02-06 16:39 UTC, islam-fawzy25 commented on javascript/javascript1/week3/Step3.js
> +   if ( notes[i].id == id ){
got it

2021-02-06 17:18 UTC, merged