Javascript/javascript2/week2
islam-fawzy25/hyf-homework pull request #9
Opened 2021-02-25 21:18 UTC by islam-fawzy25

2021-02-26 14:58 UTC, cameronjdavis requested changes

2021-02-26 14:58 UTC, cameronjdavis commented on javascript/javascript2/week2/index.html
> +    <script src="moviesArray.js"></script>
You have not committed `moviesArray.js` to this branch.

2021-02-26 14:58 UTC, cameronjdavis commented on javascript/javascript2/week2/moviesEx.js
> +const yearOfMadeMovies = movies.filter(year => (year.year >= 1980 && year.year <= 1989) ? true : false);
This will end up being a boolean (true, false), so you do not need the ternary statement.
`(year.year >= 1980 && year.year <= 1989)`

Also, `year.year` is confusing to read. Call it something like `movie`.

```suggestion
const yearOfMadeMovies = movies.filter(movie => (movie.year >= 1980 && movie.year <= 1989));
```

2021-02-26 16:03 UTC, islam-fawzy25 commented on javascript/javascript2/week2/index.html
> +    <script src="moviesArray.js"></script>
yes , i removed this page . can you help me , how can i use movies array from moviesArray.js file in main.js file ?

2021-02-27 16:24 UTC, cameronjdavis commented on javascript/javascript2/week2/index.html
> +    <script src="moviesArray.js"></script>
If you include the file like this, are the movies available to console.log(movies)?

```suggestion
    <script src="moviesArray.js"></script>
    <script src="moviesEx.js"></script>
```

2021-02-27 19:48 UTC, merged